site_name: RanCat Docs
site_author: Matthew Egan (github/mattjegan)
repo_url: https://github.com/mattjegan/rancat
repo_name: mattjegan/rancat
pages:
- Home: rancat/docs/index.md
- The RanCat Object: rancat/docs/RanCat.md
- Contributing: rancat/docs/contributing.md
theme: readthedocs
